name: Build and Deploy Weather App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'TST'
        type: choice
        options:
          - TST
          - UAT
          - PROD

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'amazoncorretto'

      - name: Run unit tests
        run: mvn test

      - name: Build Docker image
        run: docker build -t weather-app .
